### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by ghost** [bdchauvette/leipzig.js#4]
Hi,

I'd like to try out your demo for my conlang, but it doesn't work. The script demo.js gives the exception `TypeError: can't convert undefined to object` when it first runs:

![image](https://user-images.githubusercontent.com/38465404/74159616-f7944380-4c13-11ea-8d58-338f05dc3c64.png)

**Comment by bdchauvette** [comment]
Thanks for the report!

I've published a new version (0.9.0) and updated the page, so it should be working now. I had to clear my cache, but it seems to work fine on my machine.

Let me know if you still run into any issues :+1:
